#-------------------------------------------------------------------------------------
# Courier settings can be set in four different ways, in order of preference, last
# being highest priority:
#
# 1) Courier defaults
# 2) Config file options as defined below
# 3) Env variable, which are prefixed with COURIER_, ex: export COURIER_PORT=8000
# 4) Command line options, ex: courier -port 8000
#
#-------------------------------------------------------------------------------------

# What backend to use for looking up and writing data
backend = "rapidpro"

# What port courier will run on
port = 8080

# Our database connection string, right now only Postgres is supported
db = "postgres://temba:temba@localhost/temba?sslmode=disable"

# Our redis connection string, path is our database. Rapid Pro uses 15 for the database (or 10 when testing) 
redis = "redis://localhost:6379/15"

# Our spool directory for storing messages when Redis is down, this must exist and be writeable
spool_dir = "/var/spool/courier"

# Our AWS access credentials
aws_access_key_id = ""
aws_secret_access_key = ""

# The region our AWS bucket is in
s3_region = "us-east-2"

# The S3 bucket we will write our media files to
s3_attachments_bucket = "courier-test"

# prefix to our filenames for media (files will be named after the msg uuid)
s3_attachments_prefix = "media"

# the DSN token for reporting errors to sentry
sentry_dsn = ""
