package models

import (
	"fmt"
	"log/slog"
	"time"

	"github.com/nyaruka/courier/v26/runtime"
	"github.com/nyaruka/gocommon/aws/dynamo"
	"github.com/nyaruka/gocommon/httpx"
	"github.com/nyaruka/gocommon/svclogs"
)

const (
	ChannelLogTypeUnknown svclogs.Type = "unknown"
	ChannelLogTypeMsgSend svclogs.Type = "msg_send"

	// ChannelLogTypeReceive covers everything a provider sends us about a contact - a message, a channel event,
	// or a request carrying several of those. Which it was is visible in the log's own request and response, so
	// splitting it further only gave the log viewer labels too alike to tell apart.
	ChannelLogTypeReceive svclogs.Type = "receive"

	// ChannelLogTypeMsgStatus is a provider reporting on a message we sent, which is worth its own type because
	// it's the one an operator filters for when chasing a message that never left 'sent'.
	ChannelLogTypeMsgStatus svclogs.Type = "msg_status"

	ChannelLogTypeEventSend       svclogs.Type = "event_send"
	ChannelLogTypeAttachmentFetch svclogs.Type = "attachment_fetch"
	ChannelLogTypeTokenRefresh    svclogs.Type = "token_refresh"
	ChannelLogTypePageSubscribe   svclogs.Type = "page_subscribe"
	ChannelLogTypeWebhookVerify   svclogs.Type = "webhook_verify"
	ChannelLogTypeChatStart       svclogs.Type = "chat_start"
)

func ErrorResponseStatusCode() *svclogs.Error {
	return &svclogs.Error{Code: "response_status_code", Message: "Unexpected response status code."}
}

func ErrorResponseUnparseable(format string) *svclogs.Error {
	return &svclogs.Error{Code: "response_unparseable", Message: fmt.Sprintf("Unable to parse response as %s.", format)}
}

func ErrorResponseUnexpected(expected string) *svclogs.Error {
	return &svclogs.Error{Code: "response_unexpected", Message: fmt.Sprintf("Expected response to be '%s'.", expected)}
}

func ErrorResponseValueMissing(key string) *svclogs.Error {
	return &svclogs.Error{Code: "response_value_missing", Message: fmt.Sprintf("Unable to find '%s' response.", key)}
}

func ErrorMediaUnsupported(contentType string) *svclogs.Error {
	return &svclogs.Error{Code: "media_unsupported", Message: fmt.Sprintf("Unsupported attachment media type: %s.", contentType)}
}

// ErrorMediaUnresolveable is used when media is unresolveable due to the channel's specific requirements
func ErrorMediaUnresolveable(contentType string) *svclogs.Error {
	return &svclogs.Error{Code: "media_unresolveable", Message: fmt.Sprintf("Unable to find version of %s attachment compatible with channel.", contentType)}
}

func ErrorAttachmentNotDecodable() *svclogs.Error {
	return &svclogs.Error{Code: "attachment_not_decodable", Message: "Unable to decode embedded attachment data."}
}

func ErrorExternal(code, message string) *svclogs.Error {
	if message == "" {
		message = fmt.Sprintf("Service specific error: %s.", code)
	}
	return &svclogs.Error{Code: "external", ExtCode: code, Message: message}
}

// ChannelLog stores the HTTP traces and errors generated by an interaction with a channel. It records the channel's
// identity rather than the channel itself so that it can be created before the channel is resolved (e.g. webhook
// verification requests which aren't for any particular channel).
type ChannelLog struct {
	*svclogs.Log

	ChannelUUID ChannelUUID
	OrgID       OrgID
}

// NewChannelLog creates a channel log for the given channel, which can be nil for requests that aren't for any
// particular channel (e.g. webhook verification). Pass a recorder for incoming requests so the request itself is
// included in the log.
func NewChannelLog(t svclogs.Type, ch *Channel, r *httpx.Recorder, redactVals []string) *ChannelLog {
	l := &ChannelLog{Log: svclogs.New(t, r, redactVals)}
	if ch != nil {
		l.ChannelUUID = ch.UUID()
		l.OrgID = ch.OrgID()
	}
	return l
}

// NewChannelLogForIncoming creates a new channel log for an incoming request, the type of which won't be known
// until the handler completes.
func NewChannelLogForIncoming(logType svclogs.Type, ch *Channel, r *httpx.Recorder, redactVals []string) *ChannelLog {
	return NewChannelLog(logType, ch, r, redactVals)
}

// NewChannelLogForSend creates a new channel log for a message send
func NewChannelLogForSend(msg *MsgOut, redactVals []string) *ChannelLog {
	return NewChannelLog(ChannelLogTypeMsgSend, msg.Channel(), nil, redactVals)
}

// NewChannelLogForAttachmentFetch creates a new channel log for an attachment fetch
func NewChannelLogForAttachmentFetch(ch *Channel, redactVals []string) *ChannelLog {
	return NewChannelLog(ChannelLogTypeAttachmentFetch, ch, nil, redactVals)
}

// NewChannelLogForEventSend creates a new channel log for an event send
func NewChannelLogForEventSend(ch *Channel, redactVals []string) *ChannelLog {
	return NewChannelLog(ChannelLogTypeEventSend, ch, nil, redactVals)
}

// Deprecated: channel handlers should add user-facing error messages via .Error() instead
func (l *ChannelLog) RawError(err error) {
	l.Error(&svclogs.Error{Message: err.Error()})
}

const dynamoChannelLogTTL = 7 * 24 * time.Hour // 1 week

// dynamoChannelLog wraps a ChannelLog to add DynamoDB support
type dynamoChannelLog struct {
	*ChannelLog
}

func (l *dynamoChannelLog) DynamoKey() dynamo.Key {
	pk := fmt.Sprintf("cha#%s#%s", l.ChannelUUID, l.UUID[len(l.UUID)-1:]) // 16 buckets for each channel
	sk := fmt.Sprintf("log#%s", l.UUID)
	return dynamo.Key{PK: pk, SK: sk}
}

func (l *dynamoChannelLog) MarshalDynamo() (*dynamo.Item, error) {
	type DataGZ struct {
		HttpLogs []*httpx.Log     `json:"http_logs"`
		Errors   []*svclogs.Error `json:"errors"`
	}

	dataGZ, err := dynamo.MarshalJSONGZ(&DataGZ{HttpLogs: l.HttpLogs, Errors: l.Errors})
	if err != nil {
		return nil, fmt.Errorf("error encoding http logs as JSON+GZip: %w", err)
	}

	ttl := l.CreatedOn.Add(dynamoChannelLogTTL)

	return &dynamo.Item{
		Key:   l.DynamoKey(),
		OrgID: int(l.OrgID),
		TTL:   &ttl,
		Data: map[string]any{
			"type":       l.Type,
			"elapsed_ms": int(l.Elapsed / time.Millisecond),
			"created_on": l.CreatedOn,
			"is_error":   l.IsError(),
		},
		DataGZ: dataGZ,
	}, nil
}

// WriteChannelLog queues the passed in channel log to be written to storage - all errors are swallowed after
// logging since logging isn't critical
func WriteChannelLog(rt *runtime.Runtime, clog *ChannelLog) {
	log := slog.With("log_uuid", clog.UUID, "log_type", clog.Type, "channel_uuid", clog.ChannelUUID)

	capacity, err := rt.Dynamo.Main.Queue(&dynamoChannelLog{clog})
	if err != nil {
		log.Error("error queuing channel log to writer", "error", err)
		return
	}
	if capacity <= 0 {
		log.With("storage", "dynamo").Error("channel log writer buffer full")
	}

	log.Debug("channel log queued")
}
