package models

import (
	"fmt"

	"github.com/nyaruka/courier/v26/utils/clogs"
	"github.com/nyaruka/gocommon/httpx"
)

const (
	ChannelLogTypeUnknown         clogs.Type = "unknown"
	ChannelLogTypeMsgSend         clogs.Type = "msg_send"
	ChannelLogTypeEventSend       clogs.Type = "event_send"
	ChannelLogTypeMsgStatus       clogs.Type = "msg_status"
	ChannelLogTypeMsgReceive      clogs.Type = "msg_receive"
	ChannelLogTypeEventReceive    clogs.Type = "event_receive"
	ChannelLogTypeMultiReceive    clogs.Type = "multi_receive"
	ChannelLogTypeAttachmentFetch clogs.Type = "attachment_fetch"
	ChannelLogTypeTokenRefresh    clogs.Type = "token_refresh"
	ChannelLogTypePageSubscribe   clogs.Type = "page_subscribe"
	ChannelLogTypeWebhookVerify   clogs.Type = "webhook_verify"
)

func ErrorResponseStatusCode() *clogs.Error {
	return &clogs.Error{Code: "response_status_code", Message: "Unexpected response status code."}
}

func ErrorResponseUnparseable(format string) *clogs.Error {
	return &clogs.Error{Code: "response_unparseable", Message: fmt.Sprintf("Unable to parse response as %s.", format)}
}

func ErrorResponseUnexpected(expected string) *clogs.Error {
	return &clogs.Error{Code: "response_unexpected", Message: fmt.Sprintf("Expected response to be '%s'.", expected)}
}

func ErrorResponseValueMissing(key string) *clogs.Error {
	return &clogs.Error{Code: "response_value_missing", Message: fmt.Sprintf("Unable to find '%s' response.", key)}
}

func ErrorMediaUnsupported(contentType string) *clogs.Error {
	return &clogs.Error{Code: "media_unsupported", Message: fmt.Sprintf("Unsupported attachment media type: %s.", contentType)}
}

// ErrorMediaUnresolveable is used when media is unresolveable due to the channel's specific requirements
func ErrorMediaUnresolveable(contentType string) *clogs.Error {
	return &clogs.Error{Code: "media_unresolveable", Message: fmt.Sprintf("Unable to find version of %s attachment compatible with channel.", contentType)}
}

func ErrorAttachmentNotDecodable() *clogs.Error {
	return &clogs.Error{Code: "attachment_not_decodable", Message: "Unable to decode embedded attachment data."}
}

func ErrorExternal(code, message string) *clogs.Error {
	if message == "" {
		message = fmt.Sprintf("Service specific error: %s.", code)
	}
	return &clogs.Error{Code: "external", ExtCode: code, Message: message}
}

// ChannelLog stores the HTTP traces and errors generated by an interaction with a channel. It records the channel's
// identity rather than the channel itself so that it can be created before the channel is resolved (e.g. webhook
// verification requests which aren't for any particular channel).
type ChannelLog struct {
	*clogs.Log

	ChannelUUID ChannelUUID
	OrgID       OrgID
}

// NewChannelLog creates a channel log for the given channel, which can be nil for requests that aren't for any
// particular channel (e.g. webhook verification). Pass a recorder for incoming requests so the request itself is
// included in the log.
func NewChannelLog(t clogs.Type, ch *Channel, r *httpx.Recorder, redactVals []string) *ChannelLog {
	l := &ChannelLog{Log: clogs.New(t, r, redactVals)}
	if ch != nil {
		l.ChannelUUID = ch.UUID()
		l.OrgID = ch.OrgID()
	}
	return l
}

// Deprecated: channel handlers should add user-facing error messages via .Error() instead
func (l *ChannelLog) RawError(err error) {
	l.Error(&clogs.Error{Message: err.Error()})
}
